kind: Deployment
apiVersion: apps/v1
metadata:
   name: unnamed-app
   namespace: default
spec:
   replicas: 1
   selector:
      matchLabels:
         app: unnamed-app
   template:
      metadata:
         labels:
            app: unnamed-app
      spec:
         containers:
            - name: unnamed-app
              image: ghcr.io/vc0sta/unnamed-project:main
              env:
                - name: VERSION 
                  value: 1
---
apiVersion: v1
kind: Service
metadata:
   name: unnamed-app
   namespace: default
   labels:
      app: unnamed-app
spec:
   ports:
      - port: 3000
        name: unnamed-app
   selector:
      app: unnamed-app
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`testando.vcosta.dev`) && PathPrefix(`/version`)
    kind: Rule
    services:
    - name: unnamed-app
      port: 80
  tls: # This route uses TLSs
      certResolver: le
