---
apiVersion: v1
kind: Namespace
metadata:
  name: main
---
kind: Deployment
apiVersion: apps/v1
metadata:
   name: unnamed-app
   namespace: main
spec:
   replicas: 1
   selector:
      matchLabels:
         app: unnamed-app
   template:
      metadata:
         labels:
            app: unnamed-app
      spec:
         containers:
            - name: unnamed-app
              image: ghcr.io/vc0sta/unnamed-project:main
              env:
                - name: VERSION 
                  value: '2'
              ports:
                - containerPort: 8096
                  name: http-tcp
                  protocol: TCP
              imagePullPolicy: Always
         imagePullSecrets:
           - name: regcred
---
apiVersion: v1
kind: Service
metadata:
   name: unnamed-app
   namespace: main
   labels:
      app: unnamed-app
spec:
   ports:
      - port: 3000
        name: http-tcp
   selector:
      app: unnamed-app
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls
  namespace: main
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`main.vcosta.dev`)
    kind: Rule
    services:
    - name: unnamed-app
      port: 3000
  tls: # This route uses TLSs
      certResolver: le
