apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: unnamed
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: unnamed
  timeout: 60s
  url: ssh://git@github.com/vc0sta/unnamed-project
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: unnamed
  namespace: flux-system
spec:
  interval: 15m
  path: "./manifests/project/main"
  prune: true
  sourceRef:
    kind: GitRepository
    name: unnamed
